### ISSUE TITLE
web - renders blank, with no console error

### ISSUE THREAD

**Issue by biancashouse** [espresso3389/flutter_pdf_render#35]
Can see in the inspector that the js gets loaded.
Works fine on mobile (iOS simulator).
Loading pdf from memory.
Here's how I render using your api (pdfDoc is created by the pdf package):

Scaffold(
      appBar: _appbar,
      body: FutureBuilder(
        future: PdfDocument.openData(Uint8List.fromList(widget.helper.pdfDoc.save())),
        builder: (context, snapshot) {
          print('LayoutBuilder...');
          print(' ****** devicePixelRatio ${MediaQuery.of(context).devicePixelRatio}');
          return snapshot.hasData
              ? LayoutBuilder(
                  builder: (context, constraints) => ListView.builder(
                    itemCount: widget.helper.pdfDoc.document.pdfPageList.pages.length,
                    itemBuilder: (context, index) => Container(
                        margin: EdgeInsets.all(FlowchartPdfPageMobile.margin),
                        padding: EdgeInsets.all(FlowchartPdfPageMobile.padding),
                        color: Colors.black12,
                        child: PdfPageView(
                          pdfDocument: snapshot.data,
                          pageNumber: index + 1,
                        )),
                  ),
                )
              : Container();
        },
      ),
    );

**Comment by biancashouse** [comment]
Just realised, because I'm using the pdf package, my index.html already include this script:

<script src="//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.min.js"></script>
<script type="text/javascript">
  pdfjsLib.GlobalWorkerOptions.workerSrc = "//cdnjs.cloudflare.com/ajax/libs/pdf.js/2.4.456/pdf.worker.min.js";
</script>

**Comment by espresso3389** [comment]
Fixed on 1.0.5. Could you check it with 1.0.5?

**Comment by biancashouse** [comment]
Removed above, and pdf still works fine, but your pkg not rendering pdf in Chrome browser.

**Comment by biancashouse** [comment]
That was nice and quick. Great.
Renders very first page then every subsequent page is gray.
Even if I go back and reopen another pdf to view, i don't see any pages at all.
If I restart the app, I get to see the very first page of the very first pdf i choose to view.

**Comment by espresso3389** [comment]
Do you add the exact code explain in the [README.md](https://github.com/espresso3389/flutter_pdf_render#web)?

```dart
  <!-- IMPORTANT: load pdfjs files -->
  <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/build/pdf.js" type="text/javascript"></script>
  <script type="text/javascript">
    pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/build/pdf.worker.min.js";
    pdfRenderOptions = {
      // where cmaps are downloaded from
      cMapUrl: 'https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/cmaps/',
      // The cmaps are compressed in the case
      cMapPacked: true,
      // any other options for pdfjsLib.getDocument.
      // params: {}
    }
  </script>
```

`pdfRenderOptions` is important if the PDF file contains non-ASCII characters.

Or another possible problem may be missing `key` on your `PdfPageView`:

```dart
Scaffold(
  appBar: _appbar,
  body: FutureBuilder(
  future: PdfDocument.openData(Uint8List.fromList(widget.helper.pdfDoc.save())),
  builder: (context, snapshot) {
    print('LayoutBuilder...');
    print(' ****** devicePixelRatio ${MediaQuery.of(context).devicePixelRatio}');
    return snapshot.hasData
    ? LayoutBuilder(
      builder: (context, constraints) => ListView.builder(
        itemCount: snapshot.data.pages.length,
        itemBuilder: (context, index) => Container(
          margin: EdgeInsets.all(FlowchartPdfPageMobile.margin),
          padding: EdgeInsets.all(FlowchartPdfPageMobile.padding),
          color: Colors.black12,
          child: PdfPageView(
          key: ValueKey(index + 1), // We had better has some key value here
          pdfDocument: snapshot.data,
          pageNumber: index + 1,
        )),
      ),
    )
    : Container();
  },
  ),
);
```

**Comment by biancashouse** [comment]
I added the key, but still the same issue.
I see strange behaviour: if I scroll down to 2nd page of my pdf, it is gray, but if I right-click to inspect, the browser causes it to render. If I scroll back up to the first page, it is gray !
So sounds like some weird ListView issue ?

**Comment by biancashouse** [comment]
After right-clicking a page to see the chrome inspector, if you then close the inspector again, it causes another page render.

**Comment by biancashouse** [comment]
I replaced PdfPageViewer with PdfViewer:

                           child: PdfViewer(
                              key: ValueKey(index + 1),
                              doc: snapshot.data,
                            ),
 
but I got RenderConstrainedOverflowBox object was given an infinite size during layout.

I need to add a viewController and params ?

I'll continue tomorrow. Gotta go. Very late in Sydney !
Appreciate your help. Many thanks.

**Comment by espresso3389** [comment]
Additional fix landing on [1.0.6](https://pub.dev/packages/pdf_render/versions/1.0.6).
I think all the issue are completely gone. Please check it.

Thanks,

**Comment by biancashouse** [comment]
Looking good. Well done.
Could you explain what caused the issue (for my flutter education) pls.
Anyway, thank you.
looking forward to the addition of desktop support to the package... ;-)

**Comment by biancashouse** [comment]
Tested on ipad pro in simulator, and in chrome, Looking great.

**Comment by espresso3389** [comment]
@biancashouse 
> Could you explain what caused the issue (for my flutter education) pls.

Basically, the plugin depends on the Flutter's widget, named [Texture](https://api.flutter.dev/flutter/widgets/Texture-class.html), that realizes fast and efficient communication between Flutter's rendering engine and the platform dependent backend (such as Quartz on iOS/macOS).

But Flutter Web actually does not support it. So when I started porting the plugin to Flutter Web, I implemented Texture compatible widget for Web, named [PdfTextureWeb](https://github.com/espresso3389/flutter_pdf_render/blob/master/lib/src/wrappers/impls/pdf_texture_web.dart). The implementation is completely different from the original one (and somewhat slower) but it can emulate the native Texture behavior well.

And the issue is just an issue on the implementation.
